# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lincoln virus
description: > # this means to ignore newlines until "baseurl:"
  Lincoln Virus

baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
# enforce_ssl: 


t:
  en:
    menu:
      index:
        name: Home
        url: 
      news:
        name: News
        url: news/
      ea:
        name: Technical adviser REAl
        url: ea/
      friends:
        name: Friends of the project
        url: friends/
    friends_btn: Open link
    paginate:
      previous: Previous
      next: Next
  ru:
    menu:
      index:
        name: Главная
        url: ru/
      news:
        name: Новости
        url: ru/news/
      ea:
        name: Технические советники REAl
        url: ru/ea/
      friends:
        name: Друзья проекта
        url: ru/friends/
    friends_btn: Перейти на сайт
    paginate:
      previous: Назад
      next: Вперёд

total: $27,000

# index:
#   en: 
#   ru: ru/
# news:
#   en: news/
#   ru: ru/news/
# ea:
#   en: ea/
#   ru: ru/ea/
# friends:
#   en: friends/
#   ru: ru/friends/

socials:

  - icon: skype
    link: skype:chutkoy89?chat

  - icon: youtube
    link: https://www.youtube.com/channel/UCiAxh-kQbW00em5SX1I5n6Q

  - icon: google-plus
    link: https://plus.google.com/+%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9%D0%A7%D1%83%D1%82%D0%BA%D0%BE%D0%B989

  - icon: facebook-square
    link: 


per_page:
  news_list: 4
  ea_list: 6


timezone: Europe/Moscow

# paginate: 4
# paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .git
  - node_modules
