# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lincoln virus
description: > # this means to ignore newlines until "baseurl:"
  Lincoln Virus

baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
# enforce_ssl: 


t:
  en:
    menu:
      index:
        name: Home
        url: 
      news:
        name: News
        url: news/
      ea:
        name: Technical adviser “REAl”
        url: ea/
      friends:
        name: Friends of the project
        url: friends/
    friends_btn: Open link
    paginate:
      previous: Previous
      next: Next
      page: Page
      of: of
      previous_news: Previous news
      next_news: Next news
  ru:
    menu:
      index:
        name: Главная
        url: ru/
      news:
        name: Новости
        url: ru/news/
      ea:
        name: Технические советники «REAl»
        url: ru/ea/
      friends:
        name: Друзья проекта
        url: ru/friends/
    friends_btn: Перейти на сайт
    paginate:
      previous: Назад
      next: Вперёд
      page: Страница
      of: из
      previous_news: Предыдущая новость
      next_news: Следующая новость
  es:
    menu:
      index:
        name: Principal
        url: es/
      news:
        name: Novedad
        url: es/news/
      ea:
        name: Los asesores técnicos «REAl»
        url: es/ea/
      friends:
        name: Los amigos de Proyecto
        url: es/friends/
    friends_btn: Pasar a la página web
    paginate:
      previous: Atrás
      next: Adelante
      page: La página
      of: de
  cn:
    menu:
      index:
        name: 首页
        url: cn/
      news:
        name: 新闻
        url: cn/news/
      ea:
        name: “REAl”技术顾问
        url: cn/ea/
      friends:
        name: 项目伙伴
        url: cn/friends/
    friends_btn: 支持该项目
    paginate:
      previous: 返回
      next: 前进
      page: 第
      of: 页／共
      end: 页
  kr:
    menu:
      index:
        name: 홈
        url: kr/
      news:
        name: 뉴스
        url: kr/news/
      ea:
        name: 기술 고문 “REAl”
        url: kr/ea/
      friends:
        name: 프로젝트 친구
        url: kr/friends/
    friends_btn: 웹 사이트로 이동 
    paginate:
      previous: 돌아가기
      next: 앞으로
      page: 제
      of: 페이지 
      end: 의
  jp:
    menu:
      index:
        name: ホーム
        url: jp/
      news:
        name: ニュース
        url: jp/news/
      ea:
        name: 「REAl」のテクニカルアドバイザー
        url: jp/ea/
      friends:
        name: プロジェクトの協力者
        url: jp/friends/
    friends_btn: サイトに進む
    paginate:
      previous: 後ろへ
      next: 前へ
      page: ページ
      of: /
  de:
    menu:
      index:
        name: Home
        url: de/
      news:
        name: Neuigkeiten
        url: de/news/
      ea:
        name: Technikberater „REAl“
        url: de/ea/
      friends:
        name: Freunde des Projekts
        url: de/friends/
    friends_btn: Gehen Sie auf die Webseite
    paginate:
      previous: Zurück
      next: Vor
      page: Seite 
      of: von
  pt:
    menu:
      index:
        name: Página principal
        url: pt/
      news:
        name: Νotícias
        url: pt/news/
      ea:
        name: 'Consultores técnicos de "REAl"'
        url: pt/ea/
      friends:
        name: Amigos do Projeto
        url: pt/friends/
    friends_btn: Ir para o sítio
    paginate:
      previous: Voltar
      next: Avançar
      page: Página 
      of: de
  fr:
    menu:
      index:
        name: Accueil
        url: fr/
      news:
        name: Actualités
        url: fr/news/
      ea:
        name: Conseillers techniques «REAl»
        url: fr/ea/
      friends:
        name: Amis du projet
        url: fr/friends/
    friends_btn: Passer sur le site
    paginate:
      previous: Précédent
      next: Suivant
      page: Page
      of: sur

total: $0
total_link: https://www.paypal.me/chutkoy/5usd

socials:

  - icon: skype
    link: skype:chutkoy89?chat

  - icon: youtube
    link: https://www.youtube.com/channel/UCiAxh-kQbW00em5SX1I5n6Q

  - icon: google-plus
    link: https://plus.google.com/+%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9%D0%A7%D1%83%D1%82%D0%BA%D0%BE%D0%B989

  - icon: facebook-square
    link: 


per_page:
  news_list: 4
  ea_list: 6


timezone: Europe/Moscow

# paginate: 4
# paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .git
  - node_modules
