# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lincoln virus
description: > # this means to ignore newlines until "baseurl:"
  Lincoln Virus

baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
# enforce_ssl: 


menu:
  en:
    index:
      name: Home
      url: 
    news:
      name: News
      url: news/
    ea:
      name: Technical adviser REAl
      url: ea/
    friends:
      name: Friends of the project
      url: friends/
  ru:
    index:
      name: Главная
      url: ru/
    news:
      name: Новости
      url: ru/news/
    ea:
      name: Технические советники REAl
      url: ru/ea/
    friends:
      name: Друзья проекта
      url: ru/friends/

# index:
#   en: 
#   ru: ru/
# news:
#   en: news/
#   ru: ru/news/
# ea:
#   en: ea/
#   ru: ru/ea/
# friends:
#   en: friends/
#   ru: ru/friends/

# twitter_username: 
# telegram_username: 
# behance_username: 
# github_username: 
# dribbble_username: 
# linkedin_username: 
# skype_username: 
# youtube_username: 
# googleplus_username: 
# facebook_username: 
# vk_username: 

timezone: Europe/Moscow

# paginate: 4
# paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .git
  - node_modules
