# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lincoln&nbsp;virus
description: > # this means to ignore newlines until "baseurl:"
  We unite and give help to those who need it. Anyone has hobby and everyone is able to help with his favorite way of passing free time!

meta: We unite and give help to those who need it. Anyone has hobby and everyone is able to help with his favorite way of passing free time!

baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
# enforce_ssl: 


total: 5$
total_link_1: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T3KLFW2TE8SJC&source=url

t:
  en:
    menu:
      index:
        name: Home
        url: 
      about_the_virus:
        name: About the virus
        url: about_the_virus/
      projects:
        name: Projects
        url: projects/
      contacts:
        name: Contacts
        url: contacts/
      friends:
        name: Friends of the project
        url: friends/
    friends_btn: Open link
    paginate:
      previous: Previous
      next: Next
      page: Page
      of: of
      previous_news: Previous news
      next_news: Next news
  ru:
    menu:
      index:
        name: Главная
        url: ru/
      about_the_virus:
        name: О вирусе
        url: ru/about_the_virus/
      projects:
        name: Проекты
        url: ru/projects/
      contacts:
        name: Контакты
        url: ru/contacts/
      friends:
        name: Друзья проекта
        url: ru/friends/
    friends_btn: Перейти на сайт
    paginate:
      previous: Назад
      next: Вперёд
      page: Страница
      of: из
      previous_news: Предыдущая новость
      next_news: Следующая новость
  es:
    menu:
      index:
        name: Principal
        url: es/
      about_the_virus:
        name: Sobre el virus
        url: es/about_the_virus/
      projects:
        name: Proyectos
        url: es/projects/
      contacts:
        name: Contactos
        url: es/contacts/
      friends:
        name: Los amigos de Proyecto
        url: es/friends/
    friends_btn: Pasar a la página web
    paginate:
      previous: Atrás
      next: Adelante
      page: La página
      of: de
  cn:
    menu:
      index:
        name: 首页
        url: cn/
      about_the_virus:
        name: 关于病毒
        url: cn/about_the_virus/
      projects:
        name: 项目
        url: cn/projects/
      contacts:
        name: 联系方式
        url: cn/contacts/
      friends:
        name: 项目伙伴
        url: cn/friends/
    friends_btn: 支持该项目
    paginate:
      previous: 返回
      next: 前进
      page: 第
      of: 页／共
      end: 页
  kr:
    menu:
      index:
        name: 홈
        url: kr/
      about_the_virus:
        name: 바이러스에 대해서
        url: kr/about_the_virus/
      projects:
        name: 프로젝트들
        url: kr/projects/
      contacts:
        name: 콘택트 렌즈
        url: kr/contacts/
      friends:
        name: 프로젝트 친구
        url: kr/friends/
    friends_btn: 웹 사이트로 이동 
    paginate:
      previous: 돌아가기
      next: 앞으로
      page: 제
      of: 페이지 
      end: 의
  jp:
    menu:
      index:
        name: ホーム
        url: jp/
      about_the_virus:
        name: ウイルスについて
        url: jp/about_the_virus/
      projects:
        name: プロジェクト
        url: jp/projects/
      contacts:
        name: 連絡先
        url: jp/contacts/
      friends:
        name: プロジェクトの協力者
        url: jp/friends/
    friends_btn: サイトに進む
    paginate:
      previous: 後ろへ
      next: 前へ
      page: ページ
      of: /
  de:
    menu:
      index:
        name: Home
        url: de/
      about_the_virus:
        name: Über das Virus
        url: de/about_the_virus/
      projects:
        name: Projekte
        url: de/projects/
      contacts:
        name: Kontakte
        url: de/contacts/
      friends:
        name: Freunde des Projekts
        url: de/friends/
    friends_btn: Gehen Sie auf die Webseite
    paginate:
      previous: Zurück
      next: Vor
      page: Seite 
      of: von
  pt:
    menu:
      index:
        name: Página principal
        url: pt/
      about_the_virus:
        name: Sobre o vírus
        url: pt/about_the_virus/
      projects:
        name: Projetos
        url: pt/projects/
      contacts:
        name: Contatos
        url: pt/contacts/
      friends:
        name: Amigos do Projeto
        url: pt/friends/
    friends_btn: Ir para o sítio
    paginate:
      previous: Voltar
      next: Avançar
      page: Página 
      of: de
  fr:
    menu:
      index:
        name: Accueil
        url: fr/
      about_the_virus:
        name: A propos du virus
        url: fr/about_the_virus/
      projects:
        name: Projets
        url: fr/projects/
      contacts:
        name: Contacts
        url: fr/contacts/
      friends:
        name: Amis du projet
        url: fr/friends/
    friends_btn: Passer sur le site
    paginate:
      previous: Précédent
      next: Suivant
      page: Page
      of: sur


collections:
  projects:
    output: true


socials:

  - icon: skype
    link: skype:chutkoy89?call

  - icon: telegram
    link: https://t.me/chutkoy
    
  - icon: paypal
    link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T3KLFW2TE8SJC&source=url
  
  - icon: money
    link: https://qiwi.com/n/CHUTKOY
    
  - icon: play
    link: https://www.signalstart.com/analysis/pipspool/50865
    
  - icon: facebook-square
    link: https://www.facebook.com/lincolnvirus

  - icon: youtube-play
    link: https://www.youtube.com/channel/UCiAxh-kQbW00em5SX1I5n6Q
    
  - icon: address-card
    link: https://passport.webmoney.ru/asp/certview.asp?wmid=400086000803


per_page:
  news_list: 4
  ea_list: 6


timezone: Europe/Moscow

# paginate: 4
# paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .git
  - node_modules
